```mermaid
classDiagram
    class Order {
        -id: UUID;
        -items: List<OrderItem>;
        -createdAt: OffsetDateTime;
        -confirmedAt: OffsetDateTime;
        -dispatchedAt: OffsetDateTime;
        -deliveredAt: OffsetDateTime;
        -cancelledAt: OffsetDateTime;
        -totalCost: BigDecimal;
        -status: Status;
    }

    class OrderItem {
        -id: UUID;
        -inventoryItemId: UUID;
        -quantity: int;
        -cost: BigDecimal;
    }

    class Status ~ValueObject~ {
        -String value;
        +of(value: StatusType): Status
    }

    class StatusType {
        <<enumeraion>>
        PENDING;
        CONFIRMED;
        DISPATCHED;
        DELIVERED;
        CANCELLED;
    }
```